import { FormRecord, ProjectRecord, ValidationForm } from '@/types/forms';
import { FormStatus } from '@/theme';

const baseForm = (overrides: Partial<ValidationForm>): ValidationForm => ({
  id: 'temp',
  validationDate: '',
  district: '',
  nameOfProject: '',
  typeOfProject: 'FMR',
  proponent: 'Department of Agriculture / LGU',
  locationBarangay: '',
  locationMunicipality: '',
  locationProvince: '',
  scopeOfWorks: '',
  estimatedCost: '',
  estimatedLengthLinear: '',
  estimatedLengthWidth: '',
  estimatedLengthThickness: '',
  projectLinkNarrative: '',
  publicMarketName: '',
  distanceKm: '',
  agriCommodities: '',
  areaHectares: '',
  numFarmers: '',
  roadRemarks: '',
  barangaysCovered: '',
  startLatDMS: '',
  startLonDMS: '',
  endLatDMS: '',
  endLonDMS: '',
  preparedByName: '',
  preparedByDesignation: '',
  recommendedByName: '',
  notedByName: '',
  status: 'Draft',
  updatedAt: new Date().toISOString(),
  ...overrides,
});

const createFormRecord = (options: {
  id: string;
  annexTitle?: string;
  status: FormStatus;
  updatedAt: string;
  linkedProjectId?: string;
  abemisId?: string;
  qrReference?: string;
  formOverrides: Partial<ValidationForm>;
}): FormRecord => ({
  id: options.id,
  annexTitle: options.annexTitle ?? 'Annex C – Validation Form',
  status: options.status,
  updatedAt: options.updatedAt,
  linkedProjectId: options.linkedProjectId,
  abemisId: options.abemisId,
  qrReference: options.qrReference,
  data: baseForm({
    status: options.status,
    updatedAt: options.updatedAt,
    ...options.formOverrides,
  }),
});

export const dummyProjects: ProjectRecord[] = [
  {
    id: '61253',
    projectCode: '2025-R4A-QUE-INFRA-FMRDP-FMR-01540',
    title: 'Concreting of Brgy. May-It FMR, Brgy. May-it, Lucban, Quezon',
    abemisId: '61253',
    qrReference: 'QR-FMR-61253',
    zone: 'South Luzon',
    operatingUnit: 'CALABARZON (Region IV-A)',
    bannerProgram: 'Farm to Market Road Development Program',
    yearFunded: 2025,
    projectType: 'Farm-to-Market Road',
    region: 'CALABARZON (Region IV-A)',
    province: 'Quezon',
    district: '1st',
    municipality: 'Lucban',
    barangay: 'May-It',
    stage: 'Proposal',
    status: 'Implementation-ready',
    author: 'Eraño Joseph Galvez',
    quantity: '0.56000',
    quantityUnit: 'km',
    allocatedAmount: '10000000.00',
    beneficiary: null,
    prexcProgram: 'AMEFIP',
    subProgram: 'Farm-to-Market Road',
    indicatorLevel1: 'FMRs validated for construction/rehabilitation',
    indicatorLevel3: 'FMRs validated for construction/rehabilitation',
    recipientType: 'Local Government Unit',
    budgetProcess: 'Tier I',
    geotags: [
      { id: '216290', projectId: '61253', photoName: 'DA_IMG_01152025_040833 PM.jpg', url: 'https://abemis.bafe.gov.ph/infraPhotos/DA_IMG_01152025_040833 PM.jpg' },
      { id: '216291', projectId: '61253', photoName: 'DA_IMG_01152025_034314 PM.jpg', url: 'https://abemis.bafe.gov.ph/infraPhotos/DA_IMG_01152025_034314 PM.jpg' },
      { id: '216292', projectId: '61253', photoName: 'DA_IMG_01152025_034716 PM.jpg', url: 'https://abemis.bafe.gov.ph/infraPhotos/DA_IMG_01152025_034716 PM.jpg' },
      { id: '216293', projectId: '61253', photoName: 'DA_IMG_01152025_035024 PM.jpg', url: 'https://abemis.bafe.gov.ph/infraPhotos/DA_IMG_01152025_035024 PM.jpg' },
      { id: '216294', projectId: '61253', photoName: 'DA_IMG_01152025_040100 PM.jpg', url: 'https://abemis.bafe.gov.ph/infraPhotos/DA_IMG_01152025_040100 PM.jpg' },
      { id: '216295', projectId: '61253', photoName: 'DA_IMG_01152025_040439 PM.jpg', url: 'https://abemis.bafe.gov.ph/infraPhotos/DA_IMG_01152025_040439 PM.jpg' },
    ],
    proposalDocuments: [
      {
        id: '55303',
        projectId: '61253',
        fileName: '20251013112023-20250506101936-Certification of ROW_Brgy. May-It, Lucban.pdf',
        category: 'LETTER/RESOLUTION',
        url: 'https://abemis.bafe.gov.ph/infraProposalDocuments/20251013112023-20250506101936-Certification of ROW_Brgy. May-It, Lucban.pdf',
      },
      {
        id: '55304',
        projectId: '61253',
        fileName: '20250506101611-Concreting of Brgy. May-It FMR, Brgy. May-it, Lucban, Quezon.GAA2025.pdf',
        category: 'VALIDATION REPORT',
        url: 'https://abemis.bafe.gov.ph/infraProposalDocuments/20250506101611-Concreting of Brgy. May-It FMR, Brgy. May-it, Lucban, Quezon.GAA2025.pdf',
      },
      {
        id: '55305',
        projectId: '61253',
        fileName: '20250506101936-Certification of ROW_Brgy. May-It, Lucban.pdf',
        category: 'ROW DOCS',
        url: 'https://abemis.bafe.gov.ph/infraProposalDocuments/20250506101936-Certification of ROW_Brgy. May-It, Lucban.pdf',
      },
    ],
    forms: [
      createFormRecord({
        id: 'annexC-001',
        status: 'Pending Sync',
        updatedAt: '2024-10-06T09:23:00Z',
        linkedProjectId: '61253',
        abemisId: '61253',
        qrReference: 'QR-FMR-61253',
        formOverrides: {
          validationDate: '2024-10-05',
          district: '1st',
          nameOfProject: 'Concreting of Brgy. May-It FMR',
          proponent: 'LGU Lucban',
          locationBarangay: 'May-It',
          locationMunicipality: 'Lucban',
          locationProvince: 'Quezon',
          scopeOfWorks: 'Concreting',
          estimatedCost: '10,000,000',
          estimatedLengthLinear: '560',
          estimatedLengthWidth: '5',
          estimatedLengthThickness: '0.2',
          projectLinkNarrative: 'Improves access to May-It barangay markets and reduces travel time by 25%.',
          publicMarketName: 'Lucban Public Market',
          distanceKm: '3',
          agriCommodities: 'Vegetables, Root crops',
          areaHectares: '250',
          numFarmers: '310',
          roadRemarks: 'Road base partly damaged; requires full concrete upgrade.',
          barangaysCovered: 'May-It, Ilayang Iyam',
          startLatDMS: "N 14° 06' 15.12\"",
          startLonDMS: "E 121° 33' 42.12\"",
          endLatDMS: "N 14° 06' 45.23\"",
          endLonDMS: "E 121° 34' 12.34\"",
          preparedByName: 'Engr. Maria Santos',
          preparedByDesignation: 'Field Engineer',
          recommendedByName: 'Dir. Juan Dela Cruz',
          notedByName: 'Gov. Jane Smith',
          status: 'Pending Sync',
          updatedAt: '2024-10-06T09:23:00Z',
        },
      }),
    ],
  },
  {
    id: '71210',
    projectCode: '2025-R11-DVO-INFRA-FMRDP-FMR-01022',
    title: 'Rehabilitation of Purok 4 FMR, Brgy. Maligaya, Davao City',
    abemisId: '71210',
    qrReference: 'QR-FMR-71210',
    zone: 'Mindanao',
    operatingUnit: 'Davao Region (Region XI)',
    bannerProgram: 'Farm to Market Road Development Program',
    yearFunded: 2025,
    projectType: 'Farm-to-Market Road',
    region: 'Region XI',
    province: 'Davao del Sur',
    district: '2nd',
    municipality: 'Davao City',
    barangay: 'Maligaya',
    stage: 'Proposal',
    status: 'For validation',
    author: 'Engr. Tomas Reyes',
    quantity: '1.20000',
    quantityUnit: 'km',
    allocatedAmount: '15000000.00',
    beneficiary: 'Farmer cooperatives of Maligaya',
    prexcProgram: 'AMEFIP',
    subProgram: 'Farm-to-Market Road',
    indicatorLevel1: 'FMRs validated for construction/rehabilitation',
    indicatorLevel3: 'FMRs validated for construction/rehabilitation',
    recipientType: 'Local Government Unit',
    budgetProcess: 'Tier II',
    geotags: [],
    proposalDocuments: [],
    forms: [
      createFormRecord({
        id: 'annexC-010',
        status: 'Draft',
        updatedAt: '2024-11-08T08:10:00Z',
        linkedProjectId: '71210',
        abemisId: '71210',
        qrReference: 'QR-FMR-71210',
        formOverrides: {
          validationDate: '2024-11-05',
          district: '2nd',
          nameOfProject: 'Rehabilitation of Purok 4 FMR',
          proponent: 'City Government of Davao',
          locationBarangay: 'Maligaya',
          locationMunicipality: 'Davao City',
          locationProvince: 'Davao del Sur',
          scopeOfWorks: 'Rehabilitation',
          estimatedCost: '15,000,000',
          estimatedLengthLinear: '1200',
          estimatedLengthWidth: '5',
          estimatedLengthThickness: '0.2',
          projectLinkNarrative: 'Connects upland producers to Toril trading post; supports cacao logistics.',
          publicMarketName: 'Toril Trading Post',
          distanceKm: '6',
          agriCommodities: 'Cacao, Banana',
          areaHectares: '380',
          numFarmers: '420',
          roadRemarks: 'Existing gravel road washed out during typhoon; requires drainage upgrade.',
          barangaysCovered: 'Maligaya, Bago Oshiro',
          startLatDMS: "N 7° 04' 11.34\"",
          startLonDMS: "E 125° 30' 02.11\"",
          endLatDMS: "N 7° 04' 45.55\"",
          endLonDMS: "E 125° 31' 10.22\"",
          preparedByName: 'Engr. Tomas Reyes',
          preparedByDesignation: 'Project Engineer',
          recommendedByName: 'Dir. Liza Velasco',
          notedByName: 'Mayor Carlos Garcia',
          status: 'Draft',
          updatedAt: '2024-11-08T08:10:00Z',
        },
      }),
    ],
  },
];

export const standaloneDrafts: FormRecord[] = [
  createFormRecord({
    id: 'draft-unlinked-001',
    status: 'Draft',
    updatedAt: '2024-10-10T10:00:00Z',
    formOverrides: {
      id: 'draft-unlinked-001',
      nameOfProject: 'Standalone Validation – Sitio Banat',
      district: 'Unassigned District',
      locationBarangay: 'Banat',
      locationMunicipality: 'Ambaguio',
      locationProvince: 'Nueva Vizcaya',
      agriCommodities: 'Rice, Corn',
      numFarmers: '110',
      roadRemarks: 'Validation completed while offline. Awaiting attachment through QR scan or ABEMIS reference.',
    },
  }),
  createFormRecord({
    id: 'draft-unlinked-002',
    status: 'Pending Sync',
    updatedAt: '2024-10-12T08:45:00Z',
    qrReference: 'QR-STANDALONE-002',
    formOverrides: {
      id: 'draft-unlinked-002',
      nameOfProject: 'Proposed FMR – Sitio Mambede',
      district: '3rd District',
      locationBarangay: 'Mambede',
      locationMunicipality: 'Dupax del Sur',
      locationProvince: 'Nueva Vizcaya',
      agriCommodities: 'Coffee, Banana',
      numFarmers: '360',
      distanceKm: '14',
      publicMarketName: 'Dupax Sur Bagsakan',
      roadRemarks: 'Assessment done during field validation. Pending ABEMIS linkage.',
    },
  }),
];
