import { ValidationForm } from '@/types/forms';
import { FormStatus } from '@/theme';

export type ProjectRecord = {
  id: string;
  name: string;
  district: string;
  locationBarangay: string;
  locationMunicipality: string;
  locationProvince: string;
  forms: Array<{
    id: string;
    annexTitle: string;
    status: FormStatus;
    updatedAt: string;
    data: ValidationForm;
  }>;
};

const baseForm = (overrides: Partial<ValidationForm>): ValidationForm => ({
  id: 'temp',
  validationDate: '',
  district: '',
  nameOfProject: '',
  typeOfProject: 'FMR',
  proponent: 'Department of Agriculture / LGU',
  locationBarangay: '',
  locationMunicipality: '',
  locationProvince: '',
  scopeOfWorks: '',
  estimatedCost: '',
  estimatedLengthLinear: '',
  estimatedLengthWidth: '',
  estimatedLengthThickness: '',
  projectLinkNarrative: '',
  publicMarketName: '',
  distanceKm: '',
  agriCommodities: '',
  areaHectares: '',
  numFarmers: '',
  roadRemarks: '',
  barangaysCovered: '',
  startLatDMS: '',
  startLonDMS: '',
  endLatDMS: '',
  endLonDMS: '',
  preparedByName: '',
  preparedByDesignation: '',
  recommendedByName: '',
  notedByName: '',
  status: 'Draft',
  updatedAt: new Date().toISOString(),
  ...overrides,
});

export const dummyProjects: ProjectRecord[] = [
  {
    id: 'project-001',
    name: 'Concreting of FMR',
    district: '2nd District',
    locationBarangay: 'San Roque',
    locationMunicipality: 'Bayombong',
    locationProvince: 'Nueva Vizcaya',
    forms: [
      {
        id: 'annexC-001',
        annexTitle: 'Annex C – Validation Form',
        status: 'Pending Sync',
        updatedAt: '2024-10-06T09:23:00Z',
        data: baseForm({
          validationDate: '2024-10-05',
          district: '2nd District',
          nameOfProject: 'Concreting of FMR',
          proponent: 'Department of Agriculture / LGU',
          locationBarangay: 'San Roque',
          locationMunicipality: 'Bayombong',
          locationProvince: 'Nueva Vizcaya',
          scopeOfWorks: 'Concreting',
          estimatedCost: '15,500,000',
          estimatedLengthLinear: '1,200',
          estimatedLengthWidth: '4',
          estimatedLengthThickness: '0.18',
          projectLinkNarrative:
            'Located within the key production area and will serve as road linkage to existing public market (Bayombong Public Market) and approximately 8 kms away from Bayombong town proper.',
          publicMarketName: 'Bayombong Public Market',
          distanceKm: '8',
          agriCommodities: 'Rice, Corn, Vegetables',
          areaHectares: '450',
          numFarmers: '650',
          roadRemarks:
            'The road length is situated in flat to undulating terrain.\nThe road length is not passable to all types of vehicle.\nThe proposed road length connects to the existing concrete road.',
          barangaysCovered: 'San Roque, Vista Alegre, Aurora',
          startLatDMS: "N 15° 7' 23.51\"",
          startLonDMS: "E 121° 6' 26.32\"",
          endLatDMS: "N 15° 6' 56.60\"",
          endLonDMS: "E 121° 7' 12.62\"",
          preparedByName: 'Engr. Mark Paul C. Baldeo',
          preparedByDesignation: 'Project Assistant IV',
          recommendedByName: 'Engr. Alyssa V. Cruz',
          notedByName: 'Dir. Rommel D. Fermin',
          status: 'Pending Sync',
          updatedAt: '2024-10-06T09:23:00Z',
        }),
      },
      {
        id: 'annexC-002',
          annexTitle: 'Annex C – Validation Form',
        status: 'Draft',
        updatedAt: '2024-10-08T11:10:00Z',
        data: baseForm({
          validationDate: '2024-10-07',
          district: '2nd District',
          nameOfProject: 'Concreting of FMR (Phase 2)',
          proponent: 'Department of Agriculture / LGU',
          locationBarangay: 'San Roque',
          locationMunicipality: 'Bayombong',
          locationProvince: 'Nueva Vizcaya',
          scopeOfWorks: 'Reinforced shoulder',
          estimatedCost: '6,500,000',
          estimatedLengthLinear: '600',
          estimatedLengthWidth: '4',
          estimatedLengthThickness: '0.18',
          projectLinkNarrative:
            'Extension of the concreted FMR to cover upstream production clusters for vegetable transport.',
          publicMarketName: 'Bayombong Public Market',
          distanceKm: '8',
          agriCommodities: 'Vegetables',
          areaHectares: '200',
          numFarmers: '220',
          roadRemarks:
            'Road shoulders need reinforcement to improve drainage.\nAccess limited to 4-wheel vehicles during rainy season.',
          barangaysCovered: 'San Roque',
          startLatDMS: "N 15° 7' 45.12\"",
          startLonDMS: "E 121° 6' 11.21\"",
          endLatDMS: "N 15° 7' 15.34\"",
          endLonDMS: "E 121° 6' 58.02\"",
          preparedByName: 'Engr. Hannah De Vera',
          preparedByDesignation: 'Field Engineer',
          recommendedByName: 'Engr. Alyssa V. Cruz',
          notedByName: 'Dir. Rommel D. Fermin',
          status: 'Draft',
          updatedAt: '2024-10-08T11:10:00Z',
        }),
      },
    ],
  },
  {
    id: 'project-002',
    name: 'Rehabilitation of FMR',
    district: '1st District',
    locationBarangay: 'Sta. Lucia',
    locationMunicipality: 'Kasibu',
    locationProvince: 'Nueva Vizcaya',
    forms: [
      {
        id: 'annexC-003',
        annexTitle: 'Annex C – Validation Form',
        status: 'Draft',
        updatedAt: '2024-09-18T16:10:00Z',
        data: baseForm({
          validationDate: '2024-09-18',
          district: '1st District',
          nameOfProject: 'Rehabilitation of FMR',
          proponent: 'Municipal Agriculture Office',
          locationBarangay: 'Sta. Lucia',
          locationMunicipality: 'Kasibu',
          locationProvince: 'Nueva Vizcaya',
          scopeOfWorks: 'Rehabilitation',
          estimatedCost: '9,200,000',
          estimatedLengthLinear: '850',
          estimatedLengthWidth: '4',
          estimatedLengthThickness: '0.15',
          projectLinkNarrative:
            'Located within the key production area and will serve as road linkage to existing public market (Kasibu Public Market) and approximately 5 kms away from Poblacion.',
          publicMarketName: 'Kasibu Public Market',
          distanceKm: '5',
          agriCommodities: 'Banana, Coffee',
          areaHectares: '300',
          numFarmers: '514',
          roadRemarks:
            'The road length is situated in flat to undulating terrain.\nThe road length is not passable to all types of vehicle.\nThe proposed road length connects to the existing concrete road.',
          barangaysCovered: 'Sta. Lucia, Poblacion',
          startLatDMS: "N 16° 14' 09.21\"",
          startLonDMS: "E 121° 32' 45.11\"",
          endLatDMS: "N 16° 13' 51.02\"",
          endLonDMS: "E 121° 33' 02.55\"",
          preparedByName: 'Engr. Patricia Santos',
          preparedByDesignation: 'Senior Agriculturist',
          recommendedByName: 'Engr. Romy dela Cruz',
          notedByName: 'Gov. Maria Diaz',
          status: 'Draft',
          updatedAt: '2024-09-18T16:10:00Z',
        }),
      },
    ],
  },
  {
    id: 'project-003',
    name: 'Graveling of FMR',
    district: '3rd District',
    locationBarangay: 'Malasin',
    locationMunicipality: 'Dupax del Norte',
    locationProvince: 'Nueva Vizcaya',
    forms: [
      {
        id: 'annexC-004',
        annexTitle: 'Annex C – Validation Form',
        status: 'Synced',
        updatedAt: '2024-09-01T07:51:00Z',
        data: baseForm({
          validationDate: '2024-08-22',
          district: '3rd District',
          nameOfProject: 'Graveling of FMR',
          proponent: 'Provincial Engineering Office',
          locationBarangay: 'Malasin',
          locationMunicipality: 'Dupax del Norte',
          locationProvince: 'Nueva Vizcaya',
          scopeOfWorks: 'Graveling',
          estimatedCost: '6,700,000',
          estimatedLengthLinear: '900',
          estimatedLengthWidth: '4',
          estimatedLengthThickness: '0.20',
          projectLinkNarrative:
            'Located within the key production area and will serve as road linkage to existing public market (Dupax Public Market) and approximately 12 kms away from Dupax del Norte.',
          publicMarketName: 'Dupax Public Market',
          distanceKm: '12',
          agriCommodities: 'Root crops, Highland vegetables',
          areaHectares: '520',
          numFarmers: '720',
          roadRemarks:
            'The road length is situated in flat to undulating terrain.\nThe road length is not passable to all types of vehicle.\nThe proposed road length connects to the existing concrete road.',
          barangaysCovered: 'Malasin, Ineangan, Abot Molina',
          startLatDMS: "N 16° 13' 03.05\"",
          startLonDMS: "E 121° 04' 44.92\"",
          endLatDMS: "N 16° 12' 45.88\"",
          endLonDMS: "E 121° 05' 07.20\"",
          preparedByName: 'Engr. John Alexis Mercado',
          preparedByDesignation: 'Project Engineer',
          recommendedByName: 'Engr. Dianne Real',
          notedByName: 'Mayor Franklin Arce',
          status: 'Synced',
          updatedAt: '2024-09-01T07:51:00Z',
        }),
      },
    ],
  },
];
